# Generated by Django 5.0 on 2024-01-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_answer4post_images_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='postName',
        ),
    ]
