# Generated by Django 5.0 on 2024-01-19 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diver', models.CharField(max_length=20, null=True, unique=True)),
                ('logName', models.CharField(max_length=20)),
                ('diveNo', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('buddy', models.CharField(max_length=20, null=True)),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('weight', models.IntegerField()),
                ('barStart', models.FloatField()),
                ('barEnd', models.FloatField()),
                ('maxDepth', models.FloatField()),
                ('minDepth', models.FloatField()),
                ('temperature', models.FloatField()),
                ('comments', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateTimeField(null=True)),
                ('voter', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.log')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
