# Generated by Django 5.0.1 on 2024-01-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diver', models.CharField(max_length=20)),
                ('logName', models.CharField(max_length=20)),
                ('diveNo', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('buddy', models.CharField(max_length=20, null=True)),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('weight', models.IntegerField()),
                ('barStart', models.FloatField()),
                ('barEnd', models.FloatField()),
                ('maxDepth', models.FloatField()),
                ('minDepth', models.FloatField()),
                ('temperature', models.FloatField()),
                ('comments', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.log')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
