# Generated by Django 5.0.1 on 2024-01-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logName', models.CharField(max_length=20)),
                ('diveNo', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('weight', models.IntegerField()),
                ('barStart', models.FloatField()),
                ('barEnd', models.FloatField()),
                ('maxDepth', models.FloatField()),
                ('minDepth', models.FloatField()),
                ('temperature', models.FloatField()),
                ('comments', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
