# Generated by Django 5.0 on 2024-02-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_log_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='log_images/'),
        ),
    ]
