# Generated by Django 5.0 on 2024-01-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_answer_answer4logs_alter_answer4logs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer4logs',
            table='Answer4Log',
        ),
    ]
