# Generated by Django 5.0.1 on 2024-01-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='buddy',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
