# Generated by Django 5.0.1 on 2024-01-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_log_buddy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelTable(
            name='log',
            table='Logs',
        ),
        migrations.AddField(
            model_name='answer',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.log'),
        ),
    ]
