# Generated by Django 5.0.1 on 2024-01-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answer_delete_post_alter_log_table_answer_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='create_date',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
