# Generated by Django 5.0.1 on 2024-01-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answer_delete_post_alter_log_table_answer_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='create_date',
        ),
    ]
