# Generated by Django 5.0.1 on 2024-01-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_log_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
