# Generated by Django 5.0 on 2024-01-19 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('diveLicense', models.CharField(max_length=50, null=True)),
                ('is_ststMember', models.BooleanField(default=False)),
                ('studentID', models.IntegerField(null=True)),
                ('major', models.CharField(max_length=50, null=True)),
                ('kisu', models.IntegerField(null=True)),
                ('is_absence', models.BooleanField(default=False, null=True)),
                ('introduction', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('loglist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.log')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Profiles',
            },
        ),
    ]
