# Generated by Django 5.0.1 on 2024-01-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_profile_age_profile_divelicense_profile_is_absence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.DateField(null=True),
        ),
    ]
