# Generated by Django 5.0.1 on 2024-01-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_profile_age_profile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profiles',
        ),
    ]
