# Generated by Django 5.0.1 on 2024-01-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_age_alter_profile_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
