# Generated by Django 5.0.1 on 2024-01-17 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_log_diver'),
        ('user_profile', '0008_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='loglist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.log'),
        ),
    ]
